# Gather Ingredients - There appears to be a variety of fruits visible in the images, including apples, bananas, and potentially others.Preparation Tools: - Use a cutting board or a flat surface on the counter to chop the fruits. - A bowl or container for mixing the fruit salad can be seen in the images. 
objects:
- name: cooking_pan_with_black_and_white_spotty_coating
  path: /home/ubuntu/桌面/control/test_data/objects/kitchen/cooking_pan_with_black_and_white_spotty_coating.object_config.json
  position:
  - -1.72312178810915
  - 1.65
  - -3.766226893840257
  rotation:
  - 0
  - 90
  - 0
- name: chinese_tea_pot
  path: /home/ubuntu/桌面/control/test_data/objects/kitchen/chinese_tea_pot.object_config.json
  position:
  - -1.2
  - 1.65
  - -3.6
  rotation:
  - -172.14321198204672
  - 170.9466386601403
  - 136.25057185028413
- name: basic_bowl
  path: /home/ubuntu/桌面/control/test_data/objects/kitchen/basic_bowl.object_config.json
  position:
  - -1.2
  - 1.65
  - -3.6
  rotation:
  - 144.20460005337662
  - -179.7140320373722
  - 142.44175492382573
- name: fork
  path: /home/ubuntu/桌面/control/test_data/objects/kitchen/fork.object_config.json
  position:
  - -1.4494086
  - 1.65
  - -3.71685
  rotation:
  - 0
  - 90
  - 0
- name: fruit_basket_-_cytokry
  path: /home/ubuntu/桌面/control/test_data/objects/kitchen/fruit_basket_-_cytokry.object_config.json
  position:
  - -1.2
  - 1.65
  - -3.6
  rotation:
  - -132.96494147644398
  - 164.96700401598872
  - 176.43670231360136
- name: glass_cup
  path: /home/ubuntu/桌面/control/test_data/objects/kitchen/glass_cup.object_config.json
  position:
  - -1.2
  - 1.65
  - -3.6
  rotation:
  - 173.6963024643906
  - -120.82631866421781
  - 130.68155299095304
- name: kitchen_knife
  path: /home/ubuntu/桌面/control/test_data/objects/kitchen/kitchen_knife.object_config.json
  position:
  - -1.2
  - 1.65
  - -3.6
  rotation:
  - -169.05377130753982
  - 142.08276352414487
  - 165.5710800422819
- name: microwave_oven
  path: /home/ubuntu/桌面/control/test_data/objects/kitchen/microwave_oven.object_config.json
  position:
  - -1.2
  - 1.65
  - -3.6
  rotation:
  - -160.20619874125086
  - 141.92829989564547
  - 163.90813748828145
- name: wooden_cutting_board
  path: /home/ubuntu/桌面/control/test_data/objects/kitchen/wooden_cutting_board.object_config.json
  position:
  - -1.6
  - 1.65
  - -3.7
  rotation:
  - 0
  - 0
  - 0
