objects:
- name: flat_screen_tv
  path: /home/ubuntu/桌面/control/env_xq/image_attack/living_room/object/2010_flat_screen_tv.object_config.json
  position:
  - 6
  - -0.3
  - 3.5
  rotation:
  - 0
  - 0
  - 0
- name: coffee_mug_school_project
  path: /home/ubuntu/桌面/control/env_xq/image_attack/living_room/object/coffee_mug_school_project.object_config.json
  position:
  - 6.2
  - -0.7
  - 4.4
  rotation:
  - 0
  - 90
  - 0
- name: trash_can 
  path: /home/ubuntu/桌面/control/env_xq/image_attack/living_room/object/trash_can.object_config.json
  position:
  - 5.1
  - -0.7
  - 5
  rotation:
  - 0
  - 90
  - 0
- name: cradle_globe_game_ready__4k_pbr
  path: /home/ubuntu/桌面/control/env_xq/image_attack/living_room/object/cradle_globe_game_ready__4k_pbr.object_config.json
  position:
  - 6.2
  - -0.7
  - 4.7758465
  rotation:
  - 0
  - 90
  - 0
- name: vase  
  path: /home/ubuntu/桌面/control/env_xq/image_attack/living_room/object/flowers_with_the_vase.object_config.json
  position:
  - 6.7
  - -0.7
  - 4.4758465
  rotation:
  - 0
  - 0
  - 0
- name: magazines
  path: /home/ubuntu/桌面/control/env_xq/image_attack/living_room/object/vogue_magazines.object_config.json
  position:
  - 4.5
  - -0.7
  - 4.2
  rotation:
  - 0
  - 0
  - 0
- name: fuzzy_slippers 
  path: /home/ubuntu/桌面/control/env_xq/image_attack/living_room/object/simple_waves_cushionpillow.object_config.json
  position:
  - 4.5
  - -0.7
  - 4.7
  rotation:
  - 0
  - 90
  - 0

