#  Make the bed by adjusting the pillows and smoothing out the covers. Remove any items on the ottoman, like clothes or other belongings, to keep the area neat. Pick up any scattered items on the floor. Ensure the surfaces are clear of clutter for a tidier appearance.
objects:
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/aesthetic_cute_white_socks.object_config.json
  position:
  - 6.5
  - 4.2
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/sock(1).object_config.json
  position:
  - 6.3
  - 3.95
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: pillow__black
  path: test_data/objects/livingroom/pillow__black.object_config.json
  position:
  - 5.0
  - 4.5
  - 2.2
  rotation:
  - -111.63807411107685
  - 6.3565566121825725
  - 72.51359344773289
- name: pillow(2)
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/pillow(2).object_config.json
  position:
  - 5.5
  - 4.3
  - 2.5
  rotation:
  - 0
  - 0
  - 0
- name: fox_toy
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fox_toy.object_config.json
  position:
  - 5.47291996697386
  - 4.5
  - 2.2
  rotation:
  - 39.34182208191794
  - 108.09373814649325
  - -22.14937396007923
- name: cup
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/cup.object_config.json
  position:
  - 4.2758727
  - 4.4
  - 1.3
  rotation:
  - 0
  - 0
  - 0
- name: table_lamp
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/table_lamp.object_config.json
  position:
  - 4.0
  - 4.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.0
  - 4.5
  - 3.3860148245076385
  rotation:
  - -103.3165249122033
  - -38.62472197660969
  - 61.48696501991549
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.0
  - 3.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: fuzzy_slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fuzzy_slippers.object_config.json
  position:
  - 5.0
  - 4.5
  - 2.2
  rotation:
  - 3.530618331223991
  - 25.93104131410189
  - -170.93994745701954
