# You can observe that the lamp is not illuminated, and it remains the same in the subsequent images as well.
objects:
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/aesthetic_cute_white_socks.object_config.json
  position:
  - 6.5
  - 4.2
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/sock(1).object_config.json
  position:
  - 6.3
  - 3.95
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: pillow__black
  path: test_data/objects/livingroom/pillow__black.object_config.json
  position:
  - 5.0
  - 4.5
  - 2.6249805050389696
  rotation:
  - -78.62676785089396
  - -153.38280505008612
  - 8.603141619573165
- name: pillow(2)
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/pillow(2).object_config.json
  position:
  - 5.416647778524894
  - 4.5
  - 2.54334117168755
  rotation:
  - -135.89773093405435
  - -106.50787215948974
  - 128.55504687714796
- name: fox_toy
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fox_toy.object_config.json
  position:
  - 5.5784574481171205
  - 4.5
  - 2.2
  rotation:
  - 81.48826034091798
  - -152.96633645656573
  - 173.84199217709312
- name: cup
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/cup.object_config.json
  position:
  - 4.2758727
  - 4.4
  - 1.3
  rotation:
  - 0
  - 0
  - 0
- name: table_lamp
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/table_lamp.object_config.json
  position:
  - 4.0
  - 4.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.5
  - 3.5
  - 3.9
  rotation:
  - 0
  - 0
  - 0
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.0
  - 3.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: fuzzy_slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fuzzy_slippers.object_config.json
  position:
  - 6.0
  - 3.5
  - 1.2
  rotation:
  - 0
  - 0
  - 0
