#  Next to the black pillow, there is a toy that appears to be a fox.
objects:
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/aesthetic_cute_white_socks.object_config.json
  position:
  - 6.5
  - 4.2
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/sock(1).object_config.json
  position:
  - 6.3
  - 3.95
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: pillow__black
  path: test_data/objects/livingroom/pillow__black.object_config.json
  position:
  - 5.018195081138641
  - 4.5
  - 3.073419351819955
  rotation:
  - 110.71260350462092
  - -119.81294930490941
  - 139.51098619897436
- name: pillow(2)
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/pillow(2).object_config.json
  position:
  - 5.360175509290515
  - 4.5
  - 2.2885059924238647
  rotation:
  - 24.028191665641884
  - -80.24758309379436
  - -133.21601700685778
- name: fox_toy
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fox_toy.object_config.json
  position:
  - 5.0
  - 4.5
  - 2.554043736768353
  rotation:
  - 19.86822992836653
  - 99.09918896823626
  - 121.58229245818416
- name: cup
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/cup.object_config.json
  position:
  - 4.2758727
  - 4.4
  - 1.3
  rotation:
  - 0
  - 0
  - 0
- name: table_lamp
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/table_lamp.object_config.json
  position:
  - 4.0
  - 4.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.5
  - 3.5
  - 3.9
  rotation:
  - 0
  - 0
  - 0
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.0
  - 3.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: fuzzy_slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fuzzy_slippers.object_config.json
  position:
  - 6.0
  - 3.5
  - 1.2
  rotation:
  - 0
  - 0
  - 0
