#  The pillows on the bed are not neatly arranged. In the images, it appears that the pillows are somewhat disheveled and not uniformly place, indicating a casual or unmade appearance.
objects:
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/aesthetic_cute_white_socks.object_config.json
  position:
  - 6.5
  - 4.2
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/sock(1).object_config.json
  position:
  - 6.3
  - 3.95
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: pillow__black
  path: test_data/objects/livingroom/pillow__black.object_config.json
  position:
  - 5.650590936483912
  - 4.5
  - 2.943470996741702
  rotation:
  - 53.90617839980541
  - 19.918570245231933
  - -134.58337490068567
- name: pillow(2)
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/pillow(2).object_config.json
  position:
  - 5.380269894351102
  - 4.5
  - 2.2
  rotation:
  - 58.462259723579734
  - -135.44432227235643
  - 133.05036215975667
- name: fox_toy
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fox_toy.object_config.json
  position:
  - 5.0
  - 4.5
  - 2.981938263960717
  rotation:
  - 157.51482340929647
  - -134.54819444496087
  - -149.3032614608553
- name: cup
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/cup.object_config.json
  position:
  - 4.2758727
  - 4.4
  - 1.3
  rotation:
  - 0
  - 0
  - 0
- name: table_lamp
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/table_lamp.object_config.json
  position:
  - 4.0
  - 4.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.5
  - 3.5
  - 3.9
  rotation:
  - 0
  - 0
  - 0
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.0
  - 3.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: fuzzy_slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fuzzy_slippers.object_config.json
  position:
  - 6.0
  - 3.5
  - 1.2
  rotation:
  - 0
  - 0
  - 0
