#  There are three visible pillows on the bed.
objects:
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/aesthetic_cute_white_socks.object_config.json
  position:
  - 6.5
  - 4.2
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: aesthetic_cute_white_socks
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/sock(1).object_config.json
  position:
  - 6.3
  - 3.95
  - 2.8
  rotation:
  - 0
  - 90
  - 0
- name: pillow__black
  path: test_data/objects/livingroom/pillow__black.object_config.json
  position:
  - 6.0
  - 4.5
  - 2.2
  rotation:
  - -146.57597052725515
  - -110.81080371361485
  - -45.14571630493265
- name: pillow(2)
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/pillow(2).object_config.json
  position:
  - 5.015516645186849
  - 4.5
  - 2.3957180886542497
  rotation:
  - -102.70745221334583
  - 134.60738569732337
  - 51.91409050434106
- name: fox_toy
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fox_toy.object_config.json
  position:
  - 5.489254342212251
  - 4.5
  - 3.0156888266854343
  rotation:
  - -148.54935642318276
  - -50.49486131860181
  - -18.749550683705195
- name: cup
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/cup.object_config.json
  position:
  - 4.2758727
  - 4.4
  - 1.3
  rotation:
  - 0
  - 0
  - 0
- name: table_lamp
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/table_lamp.object_config.json
  position:
  - 4.0
  - 4.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.5
  - 3.5
  - 3.9
  rotation:
  - 0
  - 0
  - 0
- name: slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/slippers.object_config.json
  position:
  - 6.0
  - 3.5
  - 1.0
  rotation:
  - 0
  - 0
  - 0
- name: fuzzy_slippers
  path: /home/ubuntu/桌面/control/test_data/objects/livingroom/fuzzy_slippers.object_config.json
  position:
  - 6.0
  - 3.5
  - 1.2
  rotation:
  - 0
  - 0
  - 0
